placeholder-identifier: 'bingo'

spawn:
  world: 'lobby'
  x: 0.5
  y: 64
  z: 0.5
  yaw: 0
  pitch: 0

teams:
  priority: [ 'red', 'blue', 'yellow', 'green' ]
  red:
    prefix: ''
    suffix: ''
    color: red
  blue:
    prefix: ''
    suffix: ''
    color: blue
  yellow:
    prefix: ''
    suffix: ''
    color: yellow
  green:
    prefix: ''
    suffix: ''
    color: green

point:
  item:
    - 50
    - 40
    - 35
    - 30
    - 25
    - 20
  line:
    - 250
    - 245
    - 240
    - 235
    - 230
    - 225
    - 220
    - 215
    - 210
    - 205
    - 200